### ISSUE TITLE
Missing pathfinder module

### ISSUE THREAD

**Issue by mbhall88** [esteinig/sketchy#3]
When trying to get the help menu for `sketchy` I am getting the following error message.

```
$ sketchy -h
Traceback (most recent call last):
  File "/homes/mbhall88/.local/share/virtualenvs/sketchy-M2xsDzXY/bin/sketchy", line 11, in <module>
    load_entry_point('sketchy', 'console_scripts', 'sketchy')()
  File "/homes/mbhall88/.local/share/virtualenvs/sketchy-M2xsDzXY/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/homes/mbhall88/.local/share/virtualenvs/sketchy-M2xsDzXY/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/homes/mbhall88/.local/share/virtualenvs/sketchy-M2xsDzXY/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/homes/mbhall88/.local/share/virtualenvs/sketchy-M2xsDzXY/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/nfs/research1/zi/mbhall/Software/sketchy/sketchy/terminal/client.py", line 9, in <module>
    from .survey import survey
  File "/nfs/research1/zi/mbhall/Software/sketchy/sketchy/terminal/survey/__init__.py", line 1, in <module>
    from .commands import survey
  File "/nfs/research1/zi/mbhall/Software/sketchy/sketchy/terminal/survey/commands.py", line 4, in <module>
    from pathfinder.pipelines.data import SurveyData
ModuleNotFoundError: No module named 'pathfinder'
``` 
I assume this has something to do with your pf-survey nextflow pipeline?

**Comment by esteinig** [comment]
Closing for v0.4
